[settings]
python.uv_venv_auto = true
[env]
uv_create_args = ['--seed']
_.python.venv = { path = ".venv", create = true } # create the venv if it doesn't exist

[tools]
uv = 'latest'
python = "3.14.0"
ruff = "latest"

[tasks.install]
description = "Install all tools"
alias = "i"
run = "uv pip install -r requirements.txt"
